# Generated by Django 3.2rc1 on 2021-03-25 15:54

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32, unique=True), size=None)),
                ('model', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('text', models.CharField(max_length=1000)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('json', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(editable=False, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('mimetype', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='logbook.message')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(editable=False, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=256)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(editable=False, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(editable=False, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(editable=False, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField(editable=False, null=True)),
                ('lon', models.FloatField(editable=False, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(editable=False, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
