# Generated by Django 3.2 on 2021-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='source_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
