# Generated by Django 3.2rc1 on 2021-03-28 20:24

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import track.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, editable=False, max_length=256)),
                ('filesize', models.IntegerField(editable=False)),
                ('compression', models.CharField(blank=True, editable=False, max_length=10)),
                ('file', models.FileField(editable=False, storage=django.core.files.storage.FileSystemStorage(location='/tmp'), upload_to=track.models.get_trackfile_upload_to)),
                ('datatype', models.CharField(blank=True, editable=False, max_length=32)),
                ('sha1', models.CharField(db_index=True, editable=False, max_length=40)),
                ('starttime', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('endtime', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('trackpoint_cnt', models.IntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracksource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trackseg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('length', models.FloatField(default=0)),
                ('trackpoint_cnt', models.IntegerField()),
                ('starttime', models.DateTimeField(db_index=True, editable=False)),
                ('endtime', models.DateTimeField(db_index=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(db_index=True, geography=True, srid=4326)),
                ('trackfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracksegs', to='track.trackfile')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trackpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('ele', models.FloatField(blank=True, null=True)),
                ('hacc', models.FloatField(blank=True, null=True)),
                ('vacc', models.FloatField(blank=True, null=True)),
                ('hdop', models.FloatField(blank=True, null=True)),
                ('vdop', models.FloatField(blank=True, null=True)),
                ('pdop', models.FloatField(blank=True, null=True)),
                ('tdop', models.FloatField(blank=True, null=True)),
                ('sat', models.IntegerField(blank=True, null=True)),
                ('satavail', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(db_index=True, geography=True, srid=4326)),
                ('trackfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackpoints', to='track.trackfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trackfile',
            name='tracksource',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.tracksource'),
        ),
        migrations.AddField(
            model_name='trackfile',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trackfile',
            unique_together={('user', 'sha1')},
        ),
    ]
